#:schema node_modules/wrangler/config-schema.json
name = "java-study-group"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"
