name: Publish to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'page/**'

defaults:
  run:
    working-directory: page

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # pnpmのインストール
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

        # Node.jsのインストール
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm run pages:build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy page/.vercel/output/static --project-name=${{secrets.CLOUDFLARE_PAGE_PROJECT_ID}}
