name: Publish to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'page/**'

defaults:
  run:
    working-directory: page

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_REGION: auto
      S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      NEXT_PUBLIC_S3_HOST_NAME: ${{ secrets.NEXT_PUBLIC_S3_HOST_NAME }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm run pages:build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy page/.vercel/output/static --project-name=${{secrets.CLOUDFLARE_PAGE_PROJECT_ID}}